<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVOx9eQv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVOx9eQv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVOx9eQv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVOx9eQv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVOx9eQv\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VOx9eQv',
    'container.build_id' => '05cfdb08',
    'container.build_time' => 1602088570,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVOx9eQv');
